#!/usr/bin/env bash

if [ -f ~/.hstf.conf ]; then
    . ~/.hstf.conf
else
    echo "Create ~/.hstf.conf with HSTF_LDPRELOAD variable pointing to libvcl_ldpreload.so"
    exit 1
fi

sudo -E go test -buildvcs=false  -v $@
